mark:
  current: transition
  color:
    foreground: [255, 0, 0]
    transition: [0, 0, 255]
  index:
    foreground: 2
    transition: 1
  size:
    current: 48
    minimum: 16
    maximum: 64
resource:
  cursor:
    alpha: 128  # [0,255]
    foreground: tools/gui/misc/cursor_f.256.png
    transition: tools/gui/misc/cursor_b.256.png


