matte: all
gca:
  engine:
    type: torch
    device: cuda:0
    parameters: data/models/matte/gca-matting.pt
sim:
  num_classes: 20
  stride: 8
  engine_cls:
    type: torch
    device: cuda:0
    parameters: data/models/matte/sim.classifier.pt
  engine_sim:
    type: torch
    device: cuda:0
    parameters: data/models/matte/sim.model.pt
timi:
  engine:
    type: torch
    device: cuda:0
    parameters: data/models/matte/timi-net.pt
dim:
  engine:
    type: torch
    device: cuda:0
    parameters: data/models/matte/dim.pt
fgi:
  engine:
    type: torch
    device: cuda:0
    parameters: data/models/matte/fgi-dim.pt